# Generated by Django 5.2.3 on 2025-08-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolixContact', '0002_contactus_read_contactus_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fullName',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
