# Generated by Django 5.2.3 on 2025-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolixProducts', '0002_alter_product_active_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'مجصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
