# Generated by Django 5.2.3 on 2025-08-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolixProducts', '0003_alter_product_options'),
        ('VolixProductsCategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='VolixProductsCategory.productcategory', verbose_name='دسته بندی'),
        ),
    ]
