# Generated by Django 5.2.3 on 2025-08-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VolixProducts', '0003_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('times', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='VolixProducts.product')),
            ],
        ),
    ]
