# Generated by Django 5.2.3 on 2025-08-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolixProducts', '0004_product_categories'),
        ('VolixTag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب/تگ', 'verbose_name_plural': 'برچسب ها / تگ ها'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='VolixProducts.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='عنوان در ادرس url'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
    ]
